---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-cluster-2-config
  namespace: vault
data:
  vault.hcl: |
    ui = true

    storage "raft" {
      path    = "/raft"
      node_id = "vault-cluster-2"
      tls_skip_verify = "true" 

      retry_join {
        leader_api_addr = "http://vault-cluster-0-service.vault.svc.cluster.local:8200"
      }

      retry_join {
        leader_api_addr = "http://vault-cluster-1-service.vault.svc.cluster.local:8200"
      }
    }

    seal "transit" {
      address            = "http://vault-kms-service.vault.svc.cluster.local:8200"
      disable_renewal    = "false"
      key_name           = "vault_0"
      mount_path         = "transit/"
      tls_skip_verify    = "true"
    }

    listener "tcp" {
      address = "0.0.0.0:8200"
      cluster_address = "0.0.0.0:8200"
      tls_disable = true
      tls_disable_client_certs = true
    }

    cluster_addr = "http://vault-cluster-2-service.vault.svc.cluster.local:8201"
    api_addr = "http://vault-cluster-2-service.vault.svc.cluster.local:8200"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-cluster-2-deployment
  namespace: vault
  labels:
    app.kubernetes.io/name: vault-cluster-2
    hc-cluster: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vault-cluster-2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vault-cluster-2
    spec:
      serviceAccountName: vault-serviceaccount
      containers:
      - name: vault
        image: vault:latest
        command: ["vault"]
        args: ["server", "-config", "/etc/vault.d/vault.hcl"]
        ports:
        - containerPort: 8200
          name: api
        volumeMounts:
        - name: config
          mountPath: "/etc/vault.d/vault.hcl"
          readOnly: true
        - name: raft
          mountPath: "/raft"
        env:
        - name: VAULT_ADDR
          value: "http://0.0.0.0:8200"
        - name: VAULT_DISABLE_MLOCK
          value: "true"
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-cluster-2-unseal-token
              key: token
      volumes:
      - name: config
        configMap:
          name: vault-cluster-2-config
          items:
          - key: "vault.hcl"
            path: "vault.hcl"
      - name: raft
        emptyDir:
          sizeLimit: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: vault-cluster-2-service
  namespace: vault
spec:
  selector:
    app.kubernetes.io/name: vault-cluster-2
  type: LoadBalancer
  ports:
    - name: api-service
      protocol: TCP
      port: 8200
      targetPort: api