---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-cluster-1-config
  namespace: vault
data:
  vault.hcl: |
    ui = true

    ha_storage "raft" {
      path    = "/raft"
      node_id = "vault-cluster-1"

      retry_join {
        leader_api_addr = "http://vault-cluster-0-service.vault.svc.cluster.local:8200"
      }
    }
    
    storage "file" {
      path = "/home/vault/data"
    }

    seal "transit" {
       address            = "http://vault-kms-service.vault.svc.cluster.local:8200"
       disable_renewal    = "false"
       key_name           = "vault_1"
       mount_path         = "transit/"
       tls_skip_verify    = "true"
    }

    listener "tcp" {
      address = "0.0.0.0:8200"
      cluster_address = "0.0.0.0:8200"
      tls_disable = 1
    }

    cluster_addr = "http://vault-cluster-1-service.vault.svc.cluster.local:8201"
    api_addr = "http://vault-cluster-1-service.vault.svc.cluster.local:8200"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-cluster-1-deployment
  namespace: vault
  labels:
    app.kubernetes.io/name: vault-cluster-1
    hc-cluster: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vault-cluster-1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vault-cluster-1
    spec:
      serviceAccountName: vault-serviceaccount
      containers:
      - name: vault
        image: vault:latest
        command: ["vault"]
        args: ["server", "-config", "/etc/vault.d/vault.hcl"]
        ports:
        - containerPort: 8200
          name: api-addr
        - containerPort: 8201
          name: cluster-addr
        volumeMounts:
        - name: config
          mountPath: "/etc/vault.d/vault.hcl"
          readOnly: true
        - name: raft
          mountPath: "/raft"          
        env:
        - name: VAULT_ADDR
          value: "http://0.0.0.0:8200"
        - name: VAULT_DISABLE_MLOCK
          value: "true"
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-cluster-1-unseal-token
              key: token
      volumes:
      - name: config
        configMap:
          name: vault-cluster-1-config
          items:
          - key: "vault.hcl"
            path: "vault.hcl"
      - name: raft
        emptyDir:
          sizeLimit: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: vault-cluster-1-service
  namespace: vault
spec:
  selector:
    app.kubernetes.io/name: vault-cluster-1
  type: LoadBalancer
  ports:
    - name: api-addr
      protocol: TCP
      port: 8200
      targetPort: api-addr
    - name: cluster-addr
      protocol: TCP
      port: 8201
      targetPort: cluster-addr